#!bin/sh
sleep 60s
wget -q --spider http://google.com
if [ $? -eq 1 ]
then
        echo "Date: `date` | Network unreachable, restart device!!!" >> /root/internet_detector_logs/reboot.log
        reboot
else
        PACKET_LOSS_1=`ping -c 1 1.1.1.1 | grep packets | awk -F '%' '{print $1}' | awk -F ', ' '{print $NF}'`
        PACKET_LOSS_2=`ping -c 1 8.8.8.8 | grep packets | awk -F '%' '{print $1}' | awk -F ', ' '{print $NF}'`
        PACKET_LOSS_3=`ping -c 1 77.88.8.8 | grep packets | awk -F '%' '{print $1}' | awk -F ', ' '{print $NF}'`
        PACKET_LOSS_SUM=$(($PACKET_LOSS_1+$PACKET_LOSS_2+$PACKET_LOSS_3))
        if [ $PACKET_LOSS_SUM -ge 22 ]
        then
                echo "Date: `date` | $PACKET_LOSS_SUM% of 30 packets lost, restart device!!!" >> /root/internet_detector_logs/reboot.log
                reboot
        fi
fi
